[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# "Цунами" 
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "local splashed = SMODS.always_scores(G.play.cards[i]) or next(find_joker('Splash'))"
position = "after"
payload = """
splashed = splashed or next(SMODS.find_card('j_tsunami')) or next(SMODS.find_card('j_landslide'))
"""
match_indent = true





